format = """
$python\
$git_branch\
$git_status\
$directory\
$character"""

[hostname]
disabled = true

[python]
format = "[ $virtualenv ]($style)"
style = "fg:white bold"

[git_branch]
format = "[ ($branch) ]($style)"
symbol = ""
style = "fg:purple bold"

[git_status]
format = "[  $all_status$ahead_behind ]($style)"
style = "bg:blue fg:white bold"
ahead = "⇡${count}"
behind = "⇣${count}"
modified = "!${count}"
staged = "+${count}"
untracked = "?${count}"
deleted = "✘${count}"

[directory]
truncation_length = 3
truncate_to_repo = false
style = "bg:green fg:black bold"
format = "[ $path]($style)"

[character]
success_symbol = "[ $](bold green)"
error_symbol = "[ #](bold red)"
format = "$symbol "
